spring:
  application:
    name: catalog-service

server:
  port: 8081
  shutdown: GRACEFUL

# expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
# expose all git info
  info:
    git:
      mode: FULL
