spring:
  application:
    name: catalog-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

server:
  port: 8081
  shutdown: GRACEFUL

# expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
# expose all git info
  info:
    git:
      mode: FULL
