spring:
  application:
    name: order-service

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:25432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq}

server:
  port: 8082
  shutdown: GRACEFUL

# expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

  # expose all git info
  info:
    git:
      mode: FULL

orders:
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders
  catalog-service-url: ${CATALOG_SERVICE_URL:http://catalog-service:8081}
  publish-order-events-job-cron: "*/5 * * * * *"
  new-orders-job-cron: "*/10 * * * * *"

logging:
  level:
    org.springframework.amqp: DEBUG

resilience4j:
  retry:
    backends:
      catalog-service:
        maxAttempts: 2
        waitDuration: 2s
  circuitbreaker:
    backends:
      catalog-service:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 6
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50

